name: Lint and Test
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    #needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: pnpm lint:strict

  format:
    name: "Code Formatting Checks"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Check Formatting
        run: pnpm format:check

  types:
    name: "Typechecks"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Check Types
        run: pnpm typecheck
